_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: es
uuid: 49f8c878-4188-434f-bf99-ecb2d7adee1a
name: Drupal
mail: paulav.rodriguezr@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: null
